# This is a basic workflow that is manually triggered
name: TCM.Tools.Migration.GH
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      organization_name:
        description: 'Organization:'
        default: 'goodyear'
        required: true
      repository_name:
        description: 'New Repository Name:'
        required: true
      repository_scope:
        description: 'Scope: (public, private, or internal)'
        # Default value if no value is explicitly provided
        default: 'private'
        required: true
      existing_repo_url:
        description: 'Existing Repository URL:'
        required: true
      existing_repo_name:
        description: 'Existing Repository Name:'
        required: true
jobs:
  Migration:
    runs-on: gisvms70
    steps:
    
    - name: Create New Repository
      run: gh repo create $ORG_NAME/$REPO_NAME --$SCOPE --confirm
      env:
        ORG_NAME: ${{ github.event.inputs.organization_name }}
        REPO_NAME: ${{ github.event.inputs.repository_name }}
        GITHUB_TOKEN: ${{ secrets.REPO_MIGRATION_TOKEN }}
        SCOPE: ${{ github.event.inputs.repository_scope }}
    - name: Clone Existing
      run: |
        echo "[DEBUG] git@github.com:$ORG_NAME/$REPO_NAME.git"
        echo "[DEBUG] ${{ github.event.inputs.existing_repo_url }}"
        echo "[DEBUG] ${{ github.event.inputs.existing_repo_name }}.git"
        
        #ls -la
        #ssh -Tv git@gitlab.gis.goodyear.com
        
        rm -f -r "${{ github.event.inputs.existing_repo_name }}.git"
        
        git config --global user.email "bassaniojr._saba@goodyear.com"
        git config --global user.name "Bassi Saba"
        
        GIT_SSH_COMMAND='ssh -i /u/gisdm05/lda5148/.ssh/id_ed25519' git clone --mirror ${{ github.event.inputs.existing_repo_url }}

        #git clone --mirror ${{ github.event.inputs.existing_repo_url }}
        cd "${{ github.event.inputs.existing_repo_name }}.git"
        
        #ls -la
        
        #ssh -Tv git@github.com
        #git push --no-verify --mirror git@github.com:$ORG_NAME/$REPO_NAME.git
        
        GIT_SSH_COMMAND='ssh -i /u/gisdm05/lda5148/.ssh/id_ed25519' git push --no-verify --mirror git@github.com:$ORG_NAME/$REPO_NAME.git
      env:
        ORG_NAME: ${{ github.event.inputs.organization_name }}
        REPO_NAME: ${{ github.event.inputs.repository_name }}
